# Generated by Django 6.0.5 on 2026-05-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='reorder_level',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
