# Generated by Django 6.0.3 on 2026-05-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0002_stock_description_stock_reorder_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='distance_km',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
