# Generated by Django 6.0.3 on 2026-05-18 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0003_remove_sales_product_name_remove_sales_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='suppliercredit',
            old_name='created_at',
            new_name='date_supplied',
        ),
        migrations.RenameField(
            model_name='suppliercredit',
            old_name='amount_owed',
            new_name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='suppliercredit',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='suppliercredit',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suppliercredit',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='suppliercredit',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.supplier'),
            preserve_default=False,
        ),
    ]
