# Generated by Django 6.0.5 on 2026-05-18 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0004_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('nin_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(?:\\+256|0)[0-9]{9}$', 'Enter a valid Ugandan phone number.')])),
                ('product_name', models.CharField(choices=[('Cement', 'Cement'), ('Iron Sheets', 'Iron Sheets'), ('Iron Bars', 'Iron Bars')], max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
