# Generated by Django 6.0.5 on 2026-05-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0005_depositscheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='transport_charge',
        ),
        migrations.AddField(
            model_name='sales',
            name='receipt_no',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nyondo_app.stock'),
        ),
    ]
