# Generated by Django 6.0.5 on 2026-06-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0008_sales_is_voided_sales_void_reason_sales_voided_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.TextField(max_length=100),
        ),
    ]
