# Generated by Django 6.0.3 on 2026-06-04 06:12

from django.db import migrations


def normalize_categories(apps, schema_editor):
    """Migrate legacy capitalized category values to lowercase."""
    Stock = apps.get_model('nyondo_app', 'Stock')
    
    # Mapping of old capitalized values to new lowercase values
    category_mapping = {
        'Cement': 'cement',
        'Iron Bars': 'iron_bars',
        'Nails': 'nails',
        'Iron Sheets': 'iron_sheets',
        'Wire Mesh': 'wire_mesh',
        'Barbed Wire': 'barbed_wire',
        'Wheelbarrows': 'wheelbarrows',
        'Paint': 'paint',
        'Tools': 'tools',
        'Other': 'other',
    }
    
    # Update all records with legacy category values
    for old_value, new_value in category_mapping.items():
        Stock.objects.filter(category=old_value).update(category=new_value)


def reverse_normalize_categories(apps, schema_editor):
    """Reverse the normalization (not recommended, but available)."""
    # We won't implement this as it would lose information
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0009_alter_stock_product_name'),
    ]

    operations = [
        migrations.RunPython(normalize_categories, reverse_normalize_categories),
    ]
