# Generated by Django 6.0.5 on 2026-06-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0010_normalize_stock_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositscheme',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('cement', 'Cement'), ('iron_bars', 'Iron Bars'), ('nails', 'Nails'), ('iron_sheets', 'Iron Sheets'), ('wire_mesh', 'Wire Mesh'), ('barbed_wire', 'Barbed Wire'), ('wheelbarrows', 'Wheelbarrows'), ('paint', 'Paint'), ('tools', 'Tools'), ('other', 'Other')], max_length=50),
        ),
    ]
